routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');

// Route::get('/',[DashboardController::class,'index']);

// Route::get('/dashboard', function(){
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::get('/', [DashboardController::class,'index'])->name('dashboard');
Auth::routes(['register'=>false]);

Route::resource('products', ProductController::class);

Route::resource('product-galleries', ProductGalleryController::class);

// Route::get('/', function () {
//     return view('dashboard') ;
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;



class ProductGallery extends Model
{
    use HasFactory;

    use SoftDeletes;

    
    protected $fillable = [
        'products_id', 'photo', 'is_default'
    ];

    protected $hidden = [
        
    ];

    public function product(){
        return $this->belongsTo(Product::class,'products_id','id');
    }

    public function getPhotoAttribute($value)
    {
        return url('storage/app/public' . $value);
    }
}

app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\ProductGallery;

use App\Http\Requests\ProductGalleryRequest;
use App\Models\Product;

use Illuminate\Support\Str;

class ProductGalleryController extends Controller
{

      /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = ProductGallery::with('product')->get();

        return view('pages.product-galleries.index')->with([
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();

        return view('pages.product-galleries.create')->with([
            'products' => $products
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductGalleryRequest $request)
    {
        $data = $request->all();
        $data['photo'] = $request->file('photo')->store(
            'assets/product', 'public'
        );
        ProductGallery::create($data);
        return redirect()->route('product-galleries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/product-galleries/create.blade.php
@extends('layouts.default')

@section('content')

<div class="card"></div>
    <div class="card-header">
        <strong>Tambah Foto Barang</strong>
    </div>
    <div class="card-body card-block">
        <form action="{{route('product-galleries.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name" class="form-control-label">Nama Barang</label>
                <select name="products_id"
                        class="form-control @error('products_id') is-invalid @enderror"/>
                        @foreach ($products as $product)
                            <option value="{{$product->id}}">{{$product->name}}</option>
                        @endforeach
                       
                </select>    
                @error('products_id') <div class="text-muted">{{$message}}</div>
                @enderror    

            </div>
                     
             <div class="form-group">
                <label for="photo" class="form-control-label">Foto Barang</label>
                <input type="file"
                        name="photo"
                        value="{{old('photo')}}"
                        accept="image/*"
                        class="form-control @error('photo') is-invalid @enderror"/>
                        @error('photo') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <label for="is_default" class="form-control-label">Jadikan Default</label>
                <br>
                <label>
                    <input type="radio"
                    name="is_default"
                    value="1"
                    class="form-control @error('is_default') is-invalid @enderror"/> Ya
                </label>
                &nbsp;
                <label>
                    <input type="radio"
                    name="is_default"
                    value="0"
                    class="form-control @error('is_default') is-invalid @enderror"/> Tidak
                </label>
               
                        @error('is_default') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit" >
                    Tambah Foto Barang
                </button>
            </div>
        </form>
    </div>
</div>
    
@endsection

resources/views/pages/product-galleries/index.blade.php
@extends('layouts.default')



@section('content')
    <div class="orders">
        <div class="col">
            <div class="row-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Daftar Foto Barang</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stat order-table ov-h">
                                <table class="table">
                                    <thead>  
                                    <tr>
                                        <th>#</th>
                                        <th>Nama Barang</th>
                                        <th>Foto</th>
                                        <th>Default</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                    <tr>
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->product->name}}</td>
                                        <td>
                                            <img src="{{url('storage/'.$item->photo)}}" alt=""/>
                                        </td>
                                        <td>{{$item->is_default ? 'Ya' : 'Tidak'}}</td>
                        
                                        <td>
                                            <form action="{{route('product-galleries.destroy',$item->id)}}" method="post" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"> </i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="6" class="text-center p-5">
                                                Data Tidak tersedia
                                            </td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop