routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductGalleryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', [DashboardController::class, 'index'])->name('dashboard')->middleware('auth');

// Route::get('/',[DashboardController::class,'index']);

// Route::get('/dashboard', function(){
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::get('/', [DashboardController::class,'index'])->name('dashboard');
Auth::routes(['register'=>false]);

Route::resource('products', ProductController::class);

Route::resource('product-galleries', ProductGalleryController::class);

// Route::get('/', function () {
//     return view('dashboard') ;
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillable = [
        'name', 'type', 'description', 'price', 'slug', 'quantity'
    ];

    protected $hidden = [
        
    ];

    public function galleries (){
        return $this->hasMany(ProductGallery::class,'product_id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;

use App\Http\Requests\ProductRequest;

use Illuminate\Http\Request;

use Illuminate\Support\Str;

class ProductController extends Controller
{
      /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $items = Product::all();
        return view('pages.products.index')->with([
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $data = $request->all();
        $data['slug'] = Str::slug($request->name);

        Product::create($data);
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Product::findOrFail($id);

        return view ('pages.products.editor')->with([
            'item' => $item
        ]);
    }
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $data = $request->all();
        $data['slug'] = Str::slug($request->name);

        $item = Product::findOrFail($id);
        
        $item->update($data);

        return redirect()->route('products.index');
    }
        

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Product::findOrFail($id);

        $item->delete();

        return redirect()->route('products.index');
    }
}

resources/views/pages/products/create.blade.php
@extends('layouts.default')

@section('content')

<div class="card"></div>
    <div class="card-header">
        <strong>Tambah Barang</strong>
    </div>
    <div class="card-body card-block">
        <form action="{{route('products.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name" class="form-control-label">Nama Barang</label>
                <input type="text"
                        name="name"
                        value="{{old('name')}}"
                        class="form-control @error('name') is-invalid @enderror"/>
                        @error('name') <div class="text-muted">{{$message}}</div>
                        @enderror

            </div>
            <div class="form-group">
                <label for="type" class="form-control-label">Type Barang</label>
                <input type="text"
                        name="type"
                        value="{{old('type')}}"
                        class="form-control @error('type') is-invalid @enderror"/>
                        @error('type') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <label for="description" class="form-control-label">Deskripsi Barang</label>
                <textarea name="description" class="ckeditor form-control @error('description') is-invalid @enderror">
                    {{old('description')}}
                </textarea>
                @error('description') <div class="text-muted">{{$message}}</div>
                        @enderror
            </div>
             <div class="form-group">
                <label for="price" class="form-control-label">Harga Barang</label>
                <input price="number"
                        name="price"
                        value="{{old('price')}}"
                        class="form-control @error('price') is-invalid @enderror"/>
                        @error('price') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <label for="quantity" class="form-control-label">Qty Barang</label>
                <input quantity="number"
                        name="quantity"
                        value="{{old('quantity')}}"
                        class="form-control @error('quantity') is-invalid @enderror"/>
                        @error('quantity') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit" >
                    Tambah Barang
                </button>
            </div>
        </form>
    </div>
</div>
    
@endsection

resources/views/pages/products/editor.blade.php
@extends('layouts.default')

@section('content')

<div class="card"></div>
    <div class="card-header">
        <strong>Ubah Barang</strong>
        <small>{{$item->name}}</small>
    </div>
    <div class="card-body card-block">
        <form action="{{route('products.update',$item->id)}}" method="POST">
            @method("PUT")
            @csrf
            <div class="form-group">
                <label for="name" class="form-control-label">Nama Barang</label>
                <input type="text"
                        name="name"
                        value="{{old('name') ? old('name') : $item->name}}"
                        class="form-control @error('name') is-invalid @enderror"/>
                        @error('name') <div class="text-muted">{{$message}}</div>
                        @enderror

            </div>
            <div class="form-group">
                <label for="type" class="form-control-label">Type Barang</label>
                <input type="text"
                        name="type"
                        value="{{old('type') ? old('type') : $item->type}}"
                        class="form-control @error('type') is-invalid @enderror"/>
                        @error('type') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <label for="description" class="form-control-label">Deskripsi Barang</label>
                <textarea name="description" class="ckeditor form-control @error('description') is-invalid @enderror">
                    {{old('description') ? old('description') : $item->description}}
                </textarea>
                @error('description') <div class="text-muted">{{$message}}</div>
                        @enderror
            </div>
             <div class="form-group">
                <label for="price" class="form-control-label">Harga Barang</label>
                <input price="number"
                        name="price"
                        value="{{old('price') ? old('price') : $item->price}}"
                        class="form-control @error('price') is-invalid @enderror"/>
                        @error('price') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <label for="quantity" class="form-control-label">Qty Barang</label>
                <input quantity="number"
                        name="quantity"
                        value="{{old('quantity') ? old('quantity') : $item->quantity}}"
                        class="form-control @error('quantity') is-invalid @enderror"/>
                        @error('quantity') <div class="text-muted">{{$message}}</div>
                        @enderror                      
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit" >
                    Ubah Barang
                </button>
            </div>
        </form>
    </div>
</div>
    
@endsection

resources/views/pages/products/index.blade.php
@extends('layouts.default')



@section('content')
    <div class="orders">
        <div class="col">
            <div class="row-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Daftar Barang</h4>
                        </div>
                        <div class="card-body--">
                            <div class="table-stat order-table ov-h">
                                <table class="table">
                                    <thead>  
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Type</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                    <tr>
                                        <td>{{$item->id }}</td>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->type}}</td>
                                        <td>{{$item->price}}</td>
                                        <td>{{$item->quantity}}</td>
                                        <td>
                                            <a href="#" class="btn btn-info btn-sm">
                                                <i class="fa fa-picture-o"></i>
                                            </a>
                                        <a href="{{route('products.edit',$item->id)}}" class="btn btn-primary btn-sm">
                                                <i class="fa fa-pencil  "></i>
                                            </a>
                                            <form action="{{route('products.destroy',$item->id)}}" method="post" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"> </i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="6" class="text-center p-5">
                                                Data Tidak tersedia
                                            </td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop